create table if not exists violations (

       ViolationID integer,
       BuildingID integer,
       RegistrationID integer,
       BoroName char(2),
       Boro char(1),
       HouseNumber text,
       LowHouseNumber text,
       HighHouseNumber text,
       StreetName text,
       StreetCode text,
       Zip text,
       Apartment text,
       Story text,
       Block integer,
       Lot integer,
       ViolationClass text,
       InspectionDate date,
       ApprovedDate date,
       OriginalCertifyByDate date,
       OriginalCorrectByDate date,
       NewCertifyByDate date,
       NewCorrectByDate date,
       CertifiedDate date,
       OrderNumber text,
       NOVID integer,
       NOVDescription text,
       NOVIssuedDate date,
       GroupName text,
       SeqNo integer,
       ShortName text,
       LongName text,
       StatusOrder integer,
       CurrentStatusDate date

);

